package org.schabi.newpipe.localserver

// Reels/Shorts feed page rendering, split out of the former monolithic HtmlRenderer.java.
object HtmlRendererShorts {

    @JvmStatic
    fun renderShortsPage(serviceId: Int, isTv: Boolean): String {
        val sb = StringBuilder()
        sb.append("<style>\n")
          .append("  .sidebar-nav { display: none !important; }\n")
          .append("  .bottom-nav { display: none !important; }\n")
          .append("  header { display: none !important; }\n")
          .append("  body { background: var(--bg-color, #000) !important; color: var(--text-color, #fff); }\n")
          .append("  .shorts-viewport { position: fixed; top: 0; left: 0; right: 0; bottom: 0; overflow-y: scroll; scroll-snap-type: y mandatory; scrollbar-width: none; background: var(--bg-color, #0f0d13); z-index: 10; }\n")
          .append("  .shorts-viewport::-webkit-scrollbar { display: none; }\n")
          .append("  .shorts-card { position: relative; width: 100%; height: 100vh; scroll-snap-align: start; scroll-snap-stop: always; display: flex; justify-content: center; align-items: center; background: var(--bg-color, #000); overflow: hidden; cursor: pointer; }\n")
          .append("  .shorts-video { max-width: 100vw; max-height: 100vh; width: auto; height: auto; object-fit: contain; margin: auto; }\n")
          // On wide screens a portrait short shrinks to fit its height, leaving it centered in a
          // sea of background - but .shorts-actions/.shorts-overlay are positioned relative to
          // .shorts-card, which was still full-viewport-wide, so the like/share/save column stayed
          // pinned to the real screen edge, far from the actual video. Capping the viewport itself
          // to a phone-like column (and centering it) pulls .shorts-card - and everything absolutely
          // positioned inside it - in along with it, with no changes needed to the overlay/actions
          // CSS since they're already positioned relative to .shorts-card, not the window.
          .append("  @media (min-width: 700px) {\n")
          .append("    .shorts-viewport { max-width: 480px; left: 50%; right: auto; transform: translateX(-50%); box-shadow: 0 0 60px rgba(0,0,0,0.5); }\n")
          .append("    .shorts-video { max-width: 100%; }\n")
          .append("  }\n")
          .append("  .shorts-overlay { position: absolute; inset: 0; pointer-events: none; display: flex; flex-direction: column; justify-content: space-between; padding: 16px; background: linear-gradient(180deg, rgba(0,0,0,0.4) 0%, transparent 20%, transparent 60%, rgba(0,0,0,0.85) 100%); z-index: 10; }\n")
          .append("  .shorts-overlay * { pointer-events: auto; }\n")
          .append("  .shorts-top-bar { display: flex; justify-content: space-between; align-items: center; width: 100%; z-index: 2; }\n")
          .append("  .shorts-filter-pill { background: rgba(232, 222, 248, 0.25); backdrop-filter: blur(12px); color: #e6e1e5; padding: 6px 16px; border-radius: 100px; font-size: 13px; font-weight: 500; border: 1px solid rgba(255,255,255,0.2); font-family: 'Roboto', sans-serif; cursor: pointer; transition: background 0.2s; }\n")
          .append("  .shorts-filter-pill:hover { background: rgba(232, 222, 248, 0.4); }\n")
          .append("  .shorts-bottom-info { display: flex; flex-direction: column; gap: 10px; color: #fff; text-shadow: 0 1px 3px rgba(0,0,0,0.8); z-index: 2; margin-right: 64px; }\n")
          .append("  .shorts-author-row { display: flex; align-items: center; gap: 10px; }\n")
          .append("  .shorts-avatar { width: 40px; height: 40px; border-radius: 50%; border: 2px solid var(--logo-color, #6750A4); object-fit: cover; }\n")
          .append("  .shorts-author-name { font-size: 15px; font-weight: 600; color: #fff; text-decoration: none; }\n")
          .append("  .shorts-sub-btn { background: var(--logo-color, #6750A4); color: #fff; padding: 6px 16px; border-radius: 100px; font-size: 13px; font-weight: 600; border: none; cursor: pointer; transition: transform 0.2s; }\n")
          .append("  .shorts-sub-btn:hover { transform: scale(1.05); }\n")
          .append("  .shorts-title { font-size: 14px; font-weight: 400; line-height: 1.4; max-height: 2.8em; overflow: hidden; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; }\n")
          .append("  .shorts-actions { position: absolute; right: 16px; bottom: 32px; display: flex; flex-direction: column; gap: 20px; align-items: center; z-index: 3; }\n")
          .append("  .shorts-action-btn { background: rgba(29, 27, 32, 0.6); backdrop-filter: blur(8px); border-radius: 50%; width: 48px; height: 48px; display: flex; align-items: center; justify-content: center; color: #fff; border: 1px solid rgba(255,255,255,0.15); cursor: pointer; transition: background 0.2s, transform 0.2s; }\n")
          .append("  .shorts-action-btn:hover { background: var(--logo-color, #6750A4); transform: scale(1.1); }\n")
          .append("  .shorts-action-btn.active { color: var(--logo-color, #6750A4) !important; }\n")
          .append("  .shorts-action-label { font-size: 11px; color: #e6e1e5; margin-top: 4px; text-shadow: 0 1px 2px rgba(0,0,0,0.8); font-weight: 500; }\n")
          .append("  .shorts-back-btn { position: fixed; top: 16px; left: 16px; z-index: 100; background: var(--search-input-bg, rgba(29,27,32,0.7)); backdrop-filter: blur(8px); border-radius: 50%; width: 44px; height: 44px; display: flex; align-items: center; justify-content: center; color: var(--text-color, #fff); border: 1px solid rgba(255,255,255,0.15); cursor: pointer; text-decoration: none; transition: background 0.2s, color 0.2s; }\n")
          .append("  .shorts-back-btn:hover { background: var(--logo-color, #6750A4); color: #fff; }\n")
          .append("  .shorts-refresh-btn { position: fixed; top: 16px; right: 16px; z-index: 100; background: var(--search-input-bg, rgba(29,27,32,0.7)); backdrop-filter: blur(8px); border-radius: 50%; width: 44px; height: 44px; display: flex; align-items: center; justify-content: center; color: var(--text-color, #fff); border: 1px solid rgba(255,255,255,0.15); cursor: pointer; transition: background 0.2s, color 0.2s, transform 0.4s; }\n")
          .append("  .shorts-refresh-btn:hover { background: var(--logo-color, #6750A4); color: #fff; }\n")
          .append("  .shorts-refresh-btn.spinning { animation: spin 0.6s linear; }\n")
          .append("  .shorts-progress-bar-container { position: absolute; bottom: 0; left: 0; right: 0; height: 4px; background: rgba(255,255,255,0.25); z-index: 10; pointer-events: none; }\n")
          .append("  .shorts-progress-bar { height: 100%; width: 0%; background: var(--logo-color, #6750A4); transition: width 0.15s linear; }\n")
          .append("  @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }\n")
          .append("  @keyframes rotate { 100% { transform: rotate(360deg); } }\n")
          .append("</style>\n")
          .append("<a href=\"/\" class=\"shorts-back-btn\" title=\"Back to Home\">\n")
          .append("  <svg viewBox=\"0 0 24 24\" fill=\"currentColor\" width=\"22\" height=\"22\"><path d=\"M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z\"/></svg>\n")
          .append("</a>\n")
          .append("<button class=\"shorts-refresh-btn\" id=\"shorts-refresh-btn\" onclick=\"refreshFeed()\" title=\"Refresh feed\">\n")
          .append("  <svg viewBox=\"0 0 24 24\" fill=\"currentColor\" width=\"22\" height=\"22\"><path d=\"M17.65 6.35C16.2 4.9 14.21 4 12 4c-4.42 0-7.99 3.58-7.99 8s3.57 8 7.99 8c3.73 0 6.84-2.55 7.73-6h-2.08c-.82 2.33-3.04 4-5.65 4-3.31 0-6-2.69-6-6s2.69-6 6-6c1.66 0 3.14.69 4.22 1.78L13 11h7V4l-2.35 2.35z\"/></svg>\n")
          .append("</button>\n")
          .append("<div class=\"shorts-viewport\" id=\"shorts-container\">\n")
          .append("  <div style=\"display:flex; justify-content:center; align-items:center; height:100%; color:var(--text-color, #fff); font-family:'Roboto',sans-serif; font-size:16px;\">\n")
          .append("    <svg class=\"spinner\" viewBox=\"0 0 50 50\" width=\"40\" height=\"40\" style=\"animation:rotate 1.5s linear infinite; margin-right:12px;\"><circle cx=\"25\" cy=\"25\" r=\"20\" fill=\"none\" stroke=\"var(--logo-color, #6750A4)\" stroke-width=\"4\"></circle></svg>\n")
          .append("    Loading your personalised feed...\n")
          .append("  </div>\n")
          .append("</div>\n")
          .append("<script>\n")
          .append("  let shortsQueue = [];\n")
          .append("  let currentPage = 0;\n")
          .append("  let isLoading = false;\n")
          .append("  let noMore = false;\n")
          .append("  let isMuted = true;\n")
          .append("  let activeIndex = 0;\n")
          .append("  async function refreshFeed() {\n")
          .append("    const btn = document.getElementById('shorts-refresh-btn');\n")
          .append("    if (btn) { btn.classList.add('spinning'); }\n")
          .append("    try {\n")
          .append("      await fetch('/api/shorts/refresh?serviceId=$serviceId');\n")
          .append("    } catch(e) {}\n")
          .append("    shortsQueue = [];\n")
          .append("    currentPage = 0;\n")
          .append("    isLoading = false;\n")
          .append("    activeIndex = 0;\n")
          .append("    shortObserver = null;\n")
          .append("    const container = document.getElementById('shorts-container');\n")
          .append("    container.innerHTML = '<div style=\"display:flex;justify-content:center;align-items:center;height:100%;color:var(--text-color, #fff);font-family:\\\'Roboto\\',sans-serif;font-size:16px;\"><svg viewBox=\"0 0 50 50\" width=\"40\" height=\"40\" style=\"animation:rotate 1.5s linear infinite;margin-right:12px;\"><circle cx=\"25\" cy=\"25\" r=\"20\" fill=\"none\" stroke=\"var(--logo-color, #6750A4)\" stroke-width=\"4\"></circle></svg>Finding new videos...</div>';\n")
          .append("    setTimeout(() => {\n")
          .append("      if (btn) btn.classList.remove('spinning');\n")
          .append("      fetchShortsFeed();\n")
          .append("    }, 1500);\n")
          .append("  }\n")
          .append("  function showLoadingCard() {\n")
          .append("    const container = document.getElementById('shorts-container');\n")
          .append("    if (!container) return;\n")
          .append("    if (document.getElementById('shorts-loading-card')) return;\n")
          .append("    const card = document.createElement('div');\n")
          .append("    card.className = 'shorts-card';\n")
          .append("    card.id = 'shorts-loading-card';\n")
          .append("    card.innerHTML = `<div style=\"display:flex; flex-direction:column; justify-content:center; align-items:center; height:100%; color:var(--text-color, #fff); font-family:\\\'Roboto\\\',sans-serif; gap:16px;\"><svg class=\"spinner\" viewBox=\"0 0 50 50\" width=\"40\" height=\"40\" style=\"animation:rotate 1.5s linear infinite; margin-bottom:12px;\"><circle cx=\"25\" cy=\"25\" r=\"20\" fill=\"none\" stroke=\"var(--logo-color, #6750A4)\" stroke-width=\"4\"></circle></svg><div style=\"font-size:16px; font-weight:500;\">Loading next shorts...</div></div>`;\n")
          .append("    container.appendChild(card);\n")
          .append("  }\n")
          .append("  function removeLoadingCard() {\n")
          .append("    const card = document.getElementById('shorts-loading-card');\n")
          .append("    if (card) card.remove();\n")
          .append("  }\n")
          .append("  async function fetchShortsFeed() {\n")
          .append("    if (isLoading || noMore) return;\n")
          .append("    isLoading = true;\n")
          .append("    showLoadingCard();\n")
          .append("    try {\n")
          .append("      const res = await fetch('/api/shorts/feed?serviceId=$serviceId&page=' + currentPage);\n")
          .append("      const data = await res.json();\n")
          .append("      removeLoadingCard();\n")
          .append("      if (data && data.items && data.items.length > 0) {\n")
          .append("        const container = document.getElementById('shorts-container');\n")
          .append("        const isFirstLoad = (shortsQueue.length === 0);\n")
          .append("        if (isFirstLoad) container.innerHTML = '';\n")
          .append("        data.items.forEach(item => {\n")
          .append("          const idx = shortsQueue.length;\n")
          .append("          shortsQueue.push(item);\n")
          .append("          renderShortCard(container, item, idx);\n")
          .append("        });\n")
          .append("        currentPage++;\n")
          .append("        if (isFirstLoad) { container.scrollTop = 0; }\n")
          .append("        observeNewCards();\n")
          .append("      } else if (data && data.loading) {\n")
          .append("        removeLoadingCard();\n")
          .append("        isLoading = false;\n")
          .append("        setTimeout(fetchShortsFeed, 2000);\n")
          .append("        const container = document.getElementById('shorts-container');\n")
          .append("        if (shortsQueue.length === 0) {\n")
          .append("          container.innerHTML = '<div style=\"display:flex;flex-direction:column;justify-content:center;align-items:center;height:100%;color:var(--text-color, #fff);font-family:\\\'Roboto\\\',sans-serif;gap:16px;\"><svg viewBox=\"0 0 50 50\" width=\"48\" height=\"48\" style=\"animation:rotate 1.5s linear infinite;\"><circle cx=\"25\" cy=\"25\" r=\"20\" fill=\"none\" stroke=\"var(--logo-color, #6750A4)\" stroke-width=\"4\"></circle></svg><div style=\"font-size:16px;font-weight:500;\">Personalising your feed...</div></div>';\n")
          .append("        }\n")
          .append("        return;\n")
          .append("      } else {\n")
          .append("        noMore = true;\n")
          .append("        if (shortsQueue.length === 0) {\n")
          .append("          const container = document.getElementById('shorts-container');\n")
          .append("          container.innerHTML = '<div style=\"display:flex;flex-direction:column;justify-content:center;align-items:center;height:100%;color:var(--text-color, #fff);font-family:\\\'Roboto\\\',sans-serif;gap:16px;\"><div style=\"font-size:18px;font-weight:500;\">No reels found</div><button onclick=\"currentPage=0;noMore=false;fetchShortsFeed();\" style=\"background:var(--logo-color, #6750A4);color:#fff;border:none;padding:10px 24px;border-radius:100px;cursor:pointer;font-size:14px;\">Retry</button></div>';\n")
          .append("        }\n")
          .append("      }\n")
          .append("    } catch(e) {\n")
          .append("      removeLoadingCard();\n")
          .append("      const container = document.getElementById('shorts-container');\n")
          .append("      if (container && shortsQueue.length === 0) {\n")
          .append("        container.innerHTML = '<div style=\"display:flex;flex-direction:column;justify-content:center;align-items:center;height:100%;color:var(--text-color, #fff);font-family:\\\'Roboto\\\',sans-serif;gap:16px;\"><div style=\"font-size:18px;font-weight:500;\">Error loading reels</div><button onclick=\"fetchShortsFeed();\" style=\"background:var(--logo-color, #6750A4);color:#fff;border:none;padding:10px 24px;border-radius:100px;cursor:pointer;font-size:14px;\">Retry</button></div>';\n")
          .append("      }\n")
          .append("    }\n")
          .append("    isLoading = false;\n")
          .append("  }\n")
          // renderShortCard below builds each card's innerHTML from /api/shorts/feed JSON via
          // template literals - item.name/uploaderName/url/thumbnailUrl are real, externally
          // sourced video metadata that can contain any character. Used unescaped, an apostrophe
          // breaks out of the single-quoted onclick="...('\${item.x}'...)" JS string literals, and
          // raw HTML tags in a title would inject straight into the DOM via innerHTML.
          .append("  function escJs(s) { return String(s == null ? '' : s).replace(/\\\\/g, '\\\\\\\\').replace(/'/g, \"\\\\'\").replace(/\\n/g, '\\\\n').replace(/\\r/g, ''); }\n")
          .append("  function escHtml(s) { return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;'); }\n")
          .append("  function getAvatarColor(name) {\n")
          .append("    const colors = ['#ff5722','#e91e63','#9c27b0','#3f51b5','#2196f3','#009688','#4caf50','#ff9800'];\n")
          .append("    let h = 0; for (let c of (name||'')) h = (h * 31 + c.charCodeAt(0)) & 0xffffffff;\n")
          .append("    return colors[Math.abs(h) % colors.length];\n")
          .append("  }\n")
          .append("  function toggleMuteGlobal(event) {\n")
          .append("    if (event) event.stopPropagation();\n")
          .append("    isMuted = !isMuted;\n")
          .append("    document.querySelectorAll('.shorts-video').forEach(video => {\n")
          .append("      video.muted = isMuted;\n")
          .append("    });\n")
          .append("    updateMuteUI();\n")
          .append("  }\n")
          .append("  function updateMuteUI() {\n")
          .append("    const muteSvg = isMuted ? \n")
          .append("      '<path d=\"M16.5 12c0-1.77-1.02-3.29-2.5-4.03v2.21l2.45 2.45c.03-.21.05-.42.05-.63zm2.5 0c0 .94-.2 1.82-.54 2.64l1.51 1.51C20.63 14.91 21 13.5 21 12c0-4.28-2.99-7.86-7-8.77v2.06c2.89.86 5 3.54 5 6.71zM4.27 3L3 4.27 7.73 9H3v6h4l5 5v-6.73l4.25 4.25c-.67.52-1.42.93-2.25 1.18v2.06c1.38-.31 2.63-.95 3.69-1.81L19.73 21 21 19.73l-9-9L4.27 3zM12 4L9.91 6.09 12 8.18V4z\"/>' :\n")
          .append("      '<path d=\"M3 9v6h4l5 5V4L7 9H3zm13.5 3c0-1.77-1.02-3.29-2.5-4.03v8.05c1.48-.73 2.5-2.25 2.5-4.02zM14 3.23v2.06c2.89.86 5 3.54 5 6.71s-2.11 5.85-5 6.71v2.06c4.01-.91 7-4.49 7-8.77s-2.99-7.86-7-8.77z\"/>';\n")
          .append("    document.querySelectorAll('.mute-btn svg').forEach(svg => { svg.innerHTML = muteSvg; });\n")
          .append("    document.querySelectorAll('.mute-label').forEach(lbl => { lbl.innerText = isMuted ? 'Muted' : 'Unmuted'; });\n")
          .append("  }\n")
          .append("  function togglePlayCard(card) {\n")
          .append("    const video = card.querySelector('video');\n")
          .append("    if (video) {\n")
          .append("      if (video.paused) {\n")
          .append("        video.play().catch(e => console.log('Play failed', e));\n")
          .append("      } else {\n")
          .append("        video.pause();\n")
          .append("      }\n")
          .append("    }\n")
          .append("  }\n")
          .append("  async function toggleSave(btn, url, title, uploader, thumbnail) {\n")
          .append("    const isSaved = btn.classList.contains('active');\n")
          .append("    const action = isSaved ? 'remove' : 'add';\n")
          .append("    btn.classList.toggle('active');\n")
          .append("    let apiUrl = `/watch_later_action?action=\${action}&url=\${encodeURIComponent(url)}`;\n")
          .append("    if (action === 'add') {\n")
          .append("      apiUrl += `&title=\${encodeURIComponent(title)}&uploader=\${encodeURIComponent(uploader)}&thumbnail=\${encodeURIComponent(thumbnail)}&type=video`;\n")
          .append("    }\n")
          .append("    apiUrl += '&back=/api/shorts/feed';\n")
          .append("    try { await fetch(apiUrl); } catch (e) {}\n")
          .append("  }\n")
          .append("  function renderShortCard(container, item, idx) {\n")
          .append("    const card = document.createElement('div');\n")
          .append("    card.className = 'shorts-card';\n")
          .append("    card.dataset.index = idx;\n")
          .append("    const firstChar = (item.uploaderName || '?').charAt(0).toUpperCase();\n")
          .append("    const avatarColor = getAvatarColor(item.uploaderName);\n")
          .append("    const muteSvg = isMuted ? \n")
          .append("      '<path d=\"M16.5 12c0-1.77-1.02-3.29-2.5-4.03v2.21l2.45 2.45c.03-.21.05-.42.05-.63zm2.5 0c0 .94-.2 1.82-.54 2.64l1.51 1.51C20.63 14.91 21 13.5 21 12c0-4.28-2.99-7.86-7-8.77v2.06c2.89.86 5 3.54 5 6.71zM4.27 3L3 4.27 7.73 9H3v6h4l5 5v-6.73l4.25 4.25c-.67.52-1.42.93-2.25 1.18v2.06c1.38-.31 2.63-.95 3.69-1.81L19.73 21 21 19.73l-9-9L4.27 3zM12 4L9.91 6.09 12 8.18V4z\"/>' :\n")
          .append("      '<path d=\"M3 9v6h4l5 5V4L7 9H3zm13.5 3c0-1.77-1.02-3.29-2.5-4.03v8.05c1.48-.73 2.5-2.25 2.5-4.02zM14 3.23v2.06c2.89.86 5 3.54 5 6.71s-2.11 5.85-5 6.71v2.06c4.01-.91 7-4.49 7-8.77s-2.99-7.86-7-8.77z\"/>';\n")
          .append("    card.onclick = function() { togglePlayCard(card); };\n")
          .append("    card.innerHTML = `<video class=\"shorts-video\" id=\"short-video-\${idx}\" ontimeupdate=\"const pb = document.getElementById('shorts-progress-bar-\${idx}'); if (pb && this.duration) pb.style.width = (this.currentTime / this.duration * 100) + '%';\" loop playsinline preload=\"none\" poster=\"\${escHtml(item.thumbnailUrl || '')}\" muted></video><div class=\"shorts-overlay\"><div class=\"shorts-top-bar\"></div><div class=\"shorts-bottom-info\" onclick=\"event.stopPropagation()\"><div class=\"shorts-author-row\"><div style=\"width:40px;height:40px;border-radius:50%;border:2px solid var(--logo-color, #6750A4);background:\${avatarColor};display:flex;align-items:center;justify-content:center;font-weight:700;font-size:16px;color:#fff;flex-shrink:0;\">\${firstChar}</div><a href=\"/channel?id=\${encodeURIComponent(item.uploaderUrl || '')}\" class=\"shorts-author-name\">\${escHtml(item.uploaderName || 'Creator')}</a></div><div class=\"shorts-title\">\${escHtml(item.name || '')}</div></div><div class=\"shorts-actions\"><div style=\"text-align:center;\" onclick=\"event.stopPropagation()\"><button class=\"shorts-action-btn\" onclick=\"toggleSave(this, '\${escJs(item.url)}', '\${escJs(item.name || '')}', '\${escJs(item.uploaderName || '')}', '\${escJs(item.thumbnailUrl || '')}')\"><svg viewBox=\"0 0 24 24\" fill=\"currentColor\" width=\"24\" height=\"24\"><path d=\"M17 3H7c-1.1 0-1.99.9-1.99 2L5 21l7-3 7 3V5c0-1.1-.9-2-2-2zm0 15l-5-2.18L7 18V5h10v13z\"/></svg></button><div class=\"shorts-action-label\">Save</div></div><div style=\"text-align:center;\" onclick=\"event.stopPropagation()\"><button class=\"shorts-action-btn\" onclick=\"location.href='/watch?id=' + encodeURIComponent('\${escJs(item.url)}')\" title=\"Open in full player\"><svg viewBox=\"0 0 24 24\" fill=\"currentColor\" width=\"24\" height=\"24\"><path d=\"M19 19H5V5h7V3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z\"/></svg></button><div class=\"shorts-action-label\">Open</div></div><div style=\"text-align:center;\" onclick=\"event.stopPropagation()\"><button class=\"shorts-action-btn mute-btn\" onclick=\"toggleMuteGlobal(event)\"><svg viewBox=\"0 0 24 24\" fill=\"currentColor\" width=\"24\" height=\"24\">\${muteSvg}</svg></button><div class=\"shorts-action-label mute-label\">\${isMuted ? 'Muted' : 'Unmuted'}</div></div><div style=\"text-align:center;\" onclick=\"event.stopPropagation()\"><button class=\"shorts-action-btn\" onclick=\"shareLink('\${escJs(item.url)}', '\${escJs(item.name || '')}')\"><svg viewBox=\"0 0 24 24\" fill=\"currentColor\" width=\"24\" height=\"24\"><path d=\"M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z\"/></svg></button><div class=\"shorts-action-label\">Share</div></div></div><div class=\"shorts-progress-bar-container\"><div class=\"shorts-progress-bar\" id=\"shorts-progress-bar-\${idx}\"></div></div></div>`;\n")
          .append("    container.appendChild(card);\n")
          .append("  }\n")
          .append("  let shortObserver = null;\n")
          .append("  function observeNewCards() {\n")
          .append("    if (!shortObserver) {\n")
          .append("      const options = { root: document.getElementById('shorts-container'), threshold: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0] };\n")
          .append("      shortObserver = new IntersectionObserver((entries) => {\n")
          .append("        let bestEntry = null;\n")
          .append("        let maxRatio = 0.1;\n")
          .append("        entries.forEach(entry => {\n")
          .append("          if (entry.isIntersecting && entry.intersectionRatio > maxRatio) {\n")
          .append("            maxRatio = entry.intersectionRatio;\n")
          .append("            bestEntry = entry;\n")
          .append("          }\n")
          .append("        });\n")
          .append("        if (bestEntry) {\n")
          .append("          const idx = parseInt(bestEntry.target.dataset.index);\n")
          .append("          activeIndex = idx;\n")
          .append("          document.querySelectorAll('.shorts-video').forEach((video, vIdx) => {\n")
          .append("            if (vIdx === idx) {\n")
          .append("              if (!video.src) {\n")
          .append("                video.src = '/stream?id=' + encodeURIComponent(shortsQueue[idx].url);\n")
          .append("              }\n")
          .append("              video.muted = isMuted;\n")
          .append("              video.play().catch(e => console.log('Autoplay blocked', e));\n")
          .append("            } else {\n")
          .append("              video.pause();\n")
          .append("            }\n")
          .append("          });\n")
          .append("          if (idx >= shortsQueue.length - 2) fetchShortsFeed();\n")
          .append("        }\n")
          .append("      }, options);\n")
          .append("    }\n")
          .append("    document.querySelectorAll('.shorts-card:not([data-observed])').forEach(card => {\n")
          .append("      card.setAttribute('data-observed', '1');\n")
          .append("      shortObserver.observe(card);\n")
          .append("    });\n")
          .append("  }\n")
          .append("  let startX = 0, startY = 0;\n")
          .append("  const container = document.getElementById('shorts-container');\n")
          .append("  container.addEventListener('touchstart', (e) => { startX = e.touches[0].clientX; startY = e.touches[0].clientY; }, { passive: true });\n")
          .append("  container.addEventListener('touchend', (e) => {\n")
          .append("    const diffX = e.changedTouches[0].clientX - startX;\n")
          .append("    if (Math.abs(diffX) > 50) {\n")
          .append("      const activeVideo = document.getElementById('short-video-' + activeIndex);\n")
          .append("      if (activeVideo) activeVideo.currentTime += (diffX > 0 ? 10 : -10);\n")
          .append("    }\n")
          .append("  }, { passive: true });\n")
          .append("  document.addEventListener('keydown', (e) => {\n")
          .append("    const cards = document.querySelectorAll('.shorts-card');\n")
          .append("    if (e.key === 'ArrowDown' && activeIndex < cards.length - 1) cards[activeIndex + 1].scrollIntoView({ behavior: 'smooth' });\n")
          .append("    else if (e.key === 'ArrowUp' && activeIndex > 0) cards[activeIndex - 1].scrollIntoView({ behavior: 'smooth' });\n")
          .append("    else if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {\n")
          .append("      const v = document.getElementById('short-video-' + activeIndex);\n")
          .append("      if (v) v.currentTime += (e.key === 'ArrowRight' ? 10 : -10);\n")
          .append("    }\n")
          .append("  });\n")
          .append("  document.addEventListener('DOMContentLoaded', fetchShortsFeed);\n")
          .append("</script>\n")

        return HtmlRendererCommon.wrapInTemplate("Reels - Fathom", sb.toString(), isTv)
    }
}
